### ISSUE TITLE
Default settings of no input item/resource doesn't seem to work correctly

### ISSUE THREAD

**Issue by Dr-zzt** [scottmsul/FactorioQualityOptimizer#11]
```
> python .\scripts\factorio_solver.py -oi=quantum-processor -ab
Solving...

The problem does not have an optimal solution.
```

```
> python .\scripts\factorio_solver.py -oi iron-plate -of test_output.html        
Solving...

Solution:
Objective value = 35.11666666666667

Inputs used:
input__normal__sulfuric-acid-geyser-resource: 15.0

Machine layout:
Biter egg in Captive biter spawner: normal
Fish breeding in Biochamber: normal, uncommon, rare, epic, legendary
Nutrients from biter egg in Biochamber: normal 2Q2P
Nutrients from fish in Biochamber: normal, uncommon, rare, epic, legendary
Sulfur (recycling) in Recycler: legendary
Sulfuric acid in Cryogenic plant: legendary 8P
sulfuric-acid-geyser-mining in Pumpjack: normal
...
```

With -ii and -ir not set, isn't the solver supposed to use all resources from everywhere?

For some reason, the solver seems to misinterpret what I want.
I don't even get what's going on in the second case. How am I supposed to extract iron out of these recipes?

**Comment by scottmsul** [comment]
I hadn't made it to gleba yet when I first wrote the scripts, so I didn't really understand how agriculture worked and didn't add it to the solver. The solver can't make quantum processors because the current default inputs can't handle carbon fiber.

Now that I've finally setup agri science, I think I'll update the default settings to use jellynut and yumako as inputs with costs of 1.

**Comment by Dr-zzt** [comment]
Would you also check the case of getting iron plate out of 'everything'? The solver instructs me to use sulfuric acid but I don't think there's a way to utilize sulfuric acid to make iron plates. (If you actually look at the machine layout there then you can see that the provided recipe is close to nonsense)

**Comment by scottmsul** [comment]
> Would you also check the case of getting iron plate out of 'everything'? The solver instructs me to use sulfuric acid but I don't think there's a way to utilize sulfuric acid to make iron plates. (If you actually look at the machine layout there then you can see that the provided recipe is close to nonsense)

I was actually just looking into this exact problem. Was checking iron gears from iron plates (no module/building cost), and it found a way with "zero" iron plates, and also using sulfuric acid. That's the only recipe that involves iron in any way, so I suspect it's somehow sneakily running it in reverse.

**Comment by scottmsul** [comment]
Turns out there's a 20% minimum speed from speed penalties that I wasn't applying, so 7 prod was giving 1 - 0.15x7 = -0.05 crafting speed.

**Comment by scottmsul** [comment]
Should be fixed

**Comment by Dr-zzt** [comment]
lol that's hilarious, no wonder why I was seeing all kinds of nonsense recipes. Great!
