### ISSUE TITLE
Issue with negative quality percent

### ISSUE THREAD

**Issue by ytterbium** [scottmsul/FactorioQualityOptimizer#7]
The computation the quality probability factor in `linear_solver.py` is erroneous when the quality percent is negative (eg. with speed beacons). When this is the case. the script considers that there is negative probability of producing higher quality items, equivalent to e a recipe that consumes higher quality items. 

This problems can be mitigated by correcting the computation of `quality percent`, or adding this line in line 78 
```python
    quality_percent = max(0, quality_percent)
```

**Comment by scottmsul** [comment]
Yes, good point. I'm away from my PC at the moment, could you submit a pr? If not no worries, I can get to it tonight.

**Comment by scottmsul** [comment]
Fixed
